main: de.langgezockt.Prefix.Prefix
name: Prefix
version: 1.7.7

author: langgezockt

depend: [PermissionsEx]

commands:
  prefix:
    description: manage prefixes
    usage: /prefix [reload | add | remove] <name> <prefix>
    aliases: [tag, tags]